# Generated by Django 5.1 on 2026-05-25 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_registrationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be between 10-15 digits and can start with +', regex='^\\+?[0-9]{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be between 10-15 digits and can start with +', regex='^\\+?[0-9]{10,15}$')]),
        ),
    ]
